set guifont=Bitstream\ Vera\ Sans\ Mono\:h14"
set linespace=3
set guioptions-=T " hide toolbar
set guioptions-=m " don't show menu
set guioptions-=r " don't show scrollbars
set guioptions-=l " don't show scrollbars
set guioptions-=R " don't show scrollbars
set guioptions-=L " don't show scrollbars
set guioptions+=c " use console dialog rather than popup dialog
